# Generated by Django 4.1.4 on 2022-12-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_contact_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='portfolio_pics/'),
        ),
    ]
