# Generated by Django 4.1.4 on 2022-12-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='portfolio_pics'),
        ),
    ]
