# Generated by Django 4.1.4 on 2023-01-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
